<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

	<PropertyGroup>
		<IlcFrameworkNativePath>$(MSBuildThisFileDirectory)/framework/</IlcFrameworkNativePath>
		<IlcSdkPath>$(MSBuildThisFileDirectory)/sdk/</IlcSdkPath>
	</PropertyGroup>

	<ItemGroup>
	    <NativeSharedLibrary Include="$(MSBuildThisFileDirectory)/native/*" />
	</ItemGroup>

	<Target Name="CopyNativeLibs" BeforeTargets="Publish">
    	<Copy SourceFiles="@(NativeSharedLibrary)" DestinationFolder="$(PublishDir)"/>
  	</Target>

</Project>
