name: OpenHarmony Build

on:
  push:
    branches:
      - 'v**'
  pull_request:
    branches:
      - 'v**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      
    - name: Update Submodule
      run: |
        git submodule update --init --recursive
        
    - name: build for x64
      working-directory: ${{ github.workspace }}/scripts
      run: |
        chmod +x ./build-openharmony-x64.sh
        ./build-openharmony-x64.sh

    - name: build for arm64
      working-directory: ${{ github.workspace }}/scripts
      run: |
        chmod +x ./build-openharmony-arm64.sh
        ./build-openharmony-arm64.sh
